# Generated by Django 3.1.1 on 2022-08-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
